### ISSUE TITLE
invoke() is blindly sending parameters

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/quest-compiler#10]
CONTINUED FROM THIS ISSUE: https://github.com/KVonGit/quest-compiler/issues/4

---
I added the bit that says "invoke is blindly sending parameters" to the script just to know when that happened. Most of the time, it does not cause any issues when that happens. Tons of things use ```invoke()```, and lots of them don't need ```invoke()``` to handle parameters in any special way.

Having said that, it also usually breaks the game when that happens when a Text Processor Function is calling ```invoke()```.

---
[> Okay, I used that version of the Compiler and it says invoke is blindly sending 'parameters': again.
(I added the fix to that version of playercore.js too)
So only you have the working version of Amber's code.](https://github.com/KVonGit/quest-compiler/issues/9#issuecomment-2291263184)

When that happens, it should also print whatever the value of ```parameters``` is directly after "Invoke is blindly sending parameters."

Did you notice if that happened? If so, what was the value of ```parameters```?

Or can you share this game file for me to investigate things?

**Comment by tass23** [comment]
> > I tested your idea using the QuestCompiler.exe inside the Compiler folder instead, and we have a MID problem:
> 
> That one doesn't work.
> 
> This is where to always get the up-to-date compiler: https://github.com/KVonGit/quest-compiler/tree/master/QuestCompiler/bin/Unofficial%20Release
> 
> Right now, the current unofficial release is this: https://github.com/KVonGit/quest-compiler/raw/master/QuestCompiler/bin/Unofficial%20Release/Quest%20Compiler%20Unofficial%20Release.6.5.8992.36624.zip

Crap, I just downloaded the entire repo. Well, at least I have two copies of the repo in case we need to go backwards!

Okay, so now I got the right thing, and I'm still seeing the invoke error, looks like referencing the same thing?
```
invoke is blindly sending 'parameters': [game.js:2090:21](file:///C:/Users/Adam/Desktop/TE-To%20Kill%20A%20Mongbat%20(NPC)/Compiled/game.js)
Object { result: false }
​
result: false
​
<prototype>: Object { … }
```

**Comment by KVonGit** [comment]
> I uploaded an archive of the whole game folder here:

Word up. Downloading now, then investigating.

**Comment by KVonGit** [comment]
```vb
    Public Sub InvokeScript(functionName As String, ParamArray args() As Object)
        Dim script As String
        If args Is Nothing Then
            script = String.Format("{0}()", functionName)
        Else
            Dim stringArgs = From arg In args
                             Select (GetScriptParameter(arg))
            script = String.Format("{0}({1})", functionName, String.Join(",", stringArgs))
        End If
        SyncLock m_buffer
            m_buffer.Add(Sub() ctlWebView.ExecuteScriptAsync(script))
        End SyncLock
    End Sub

    Private Function GetScriptParameter(arg As Object) As String
        If arg Is Nothing Then
            Return "null"
        ElseIf TypeOf arg Is String Then
            Dim argString = DirectCast(arg, String)
            Return """" + argString.Replace("\", "\\").Replace("""", "\""").Replace(Chr(13), "").Replace(Chr(10), "") + """"
        ElseIf TypeOf arg Is Integer Then
            Dim argInt = DirectCast(arg, Integer)
            Return argInt.ToString(System.Globalization.CultureInfo.InvariantCulture)
        ElseIf TypeOf arg Is Double Then
            Dim argInt = DirectCast(arg, Double)
            Return argInt.ToString(System.Globalization.CultureInfo.InvariantCulture)
        ElseIf TypeOf arg Is Boolean Then
            Return If(DirectCast(arg, Boolean), "true", "false")
        ElseIf TypeOf arg Is IDictionary(Of String, String) Then
            ' Copy dictionary to work around an InvalidCastException when serializing
            Dim copy = New Dictionary(Of String, String)(DirectCast(arg, IDictionary(Of String, String)))
            Return Newtonsoft.Json.JsonConvert.SerializeObject(copy)
        Else
            Return Newtonsoft.Json.JsonConvert.SerializeObject(arg)
        End If
    End Function
```
