### ISSUE TITLE
How to Be Sure Your game.js File Is the Most Recent Version

### ISSUE THREAD

**Issue by KVonGit** [KVonGit/quest-compiler#12]
**NOTE:**

You usually do not need to do this.

The only time you need to do this is when we have been actively updating functions in the main **game.js** file in this Quest Compiler repo, and I say, "hey. Go get the updated **game.js**."

---
The most current version of game.js is always here:

https://github.com/KVonGit/quest-compiler/raw/master/Compiler/game.js

---
You can view the file without downloading first on Github here:
https://github.com/KVonGit/quest-compiler/blob/master/Compiler/game.js

---
Look at the game.js version at the beginning of the file to know if it is a newer version than your game.js.

```js
/*
Quest Compiler
KVMod
version 6.5

game.js version 20240814.1555
*/
```

This one was updated on 8-14-2024, at 15:55 UTC time.

**Comment by KVonGit** [comment]
>Alright, I copied that and replaced the game.js in the current compiler, this time the invoke error is gone

The **game.js** in the current unofficial release and the **game.js** in the "Compiler" directory should be identical.

Just checked that by running a DIFF with Code:

![image](https://github.com/user-attachments/assets/92536630-8932-45b6-b7ec-fda9d82d9f3c)

---
It sounds like maybe you are getting your folders crossed up when opening the Quest compiler. I know I was doing that 20 times a day, until I created a folder called ARCHIVE and dropped every old folder I was working with into ARCHIVE every time I began to work with a newer version.

I would have at least 3 folders named "Quest Converter 6.5 - Copy Copy Copy" going on before that, hehe.

I also get my Schwartz twisted between game folders in my Github folder and updated version of those same game folders that I have downloaded and extracted as zips in my Downloads folder.

Calgon, take me away!

**Comment by tass23** [comment]
Okay, so originally I grabbed the whole repo, which I assumed had the updated game.js in one of the Compiler-related folders.
Then I copied the game.js that you linked, and overwrote the one inside the unzipped repo folder.

So, where am I? LOL
Should I be using the repo, and still updating the game.js inside the repo folder, or should I be using the direct raw of the compiler portable which has the game.js inside that you are updating?

**Comment by KVonGit** [comment]
Haha, yeah, it's not very straightforward.

Normally, all you need is the most recent file from this directory in the repo:

https://github.com/KVonGit/quest-compiler/tree/master/QuestCompiler/bin/Unofficial%20Release

You just unzip that and run the compiler from that folder henceforth. No need to take any extra steps.

---
...UNLESS you and I are actively working on something that is in **game.js** by default (meaning it's not an issue specifically in a converted game's **game.js** file, but an issue that is in the default **game.js** file in your Quest Compiler 6.5 folder).

Sometimes, when we are addressing issues in the default **game.js** file, I update the file in [the Compiler directory](https://github.com/KVonGit/quest-compiler/tree/master/Compiler) in this repo and tell you to update the file in your Quest Compiler 6.5 folder with the new one and try converting with the updated **game.js**.

So, you only need to overwrite the main **game.js** file if I tell you to do so. Otherwise, just run Quest Compiler 6.5 directly after unzipping its Unofficial Release folder.

---
Sometimes, when I fix something, I only have to update **game.js**. 

Some of those times, you and I are actively working on that issue, and I'll ask you to update your **game.js** file to test from your end before I make a Release archive with the updated **game.js**.

When this happens, I don't have to rebuild the project in VS. I just update **game.js** and create a new Unofficial Release and upload it to the repo. In these cases, you could technically just update your **game.js** file locally and not worry with anything else.

Other times, I have to modify code that is hard-coded into the C# stuff in Quest Compiler 6.5. In those cases, you have to download my new unofficial release to get those changes. In these cases, the binary files are updated, not just **game.js** (if **game.js** is even updated at all).

---
I think I'm being confusing. Did I explain it well?

**Comment by KVonGit** [comment]
Well... Normally, you would only see one **game.js** as an end user.

The Compiler/game.js is only used by Visual Studio to build the program.

So, VS just copies Compiler.game.js to QuestCompiler/bin/Release/game.js when it builds the project.

All the end user will ever get is the Release folder. Software guys just copy that Release folder and rename it like "Quest Compiler 6.5 - Release BlahBlahBlah" then zip it for the end user to use as a "portable" program.

In Quest, when you build the Release, it uses ISS to create the quest.exe installer. All ISS does is zip the Release folder and it has a file that tells it to copy those files to "Program Files/Quest/"

...but all anyone is ever getting from Quest or the Quest Compiler is really just the Release folder.

---
Oh yeah... and that's why the game.js in Compiler is usually identical to the one in QuestCompiler/bin/Release. Unless I have just updated the main game.js file (in Compiler) in order to build an updated release.

**Comment by tass23** [comment]
I watched the BUILD video. Thank you for that! However, it doesn't work for me. I got 2 warnings:
`Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" /><bindingRedirect oldVersion="0.0.0.0-13.0.0.0" newVersion="13.0.0.0" /></dependentAssembly></assemblyBinding>	QuestJSWeb	`		

`No way to resolve conflict between "Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" and "Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed". Choosing "Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" arbitrarily.	QuestJSWeb		`	

So I've got a different set up than you. VS14, I may not have all the updated support software packages that you do...?

**Comment by KVonGit** [comment]
>So I've got a different set up than you. VS14, I may not have all the updated support software packages that you do...?

That's probably it. I got Visual Studio Community 2022. (It was the oldest version still available for download, haha.)

https://visualstudio.microsoft.com/vs/community/

As of writing this, that link takes you directly to the VS Community 2022 page, and the Download button is right there without having to scroll.

---
Why are you building it, out of curiosity? Just to see if you can? (If so, I whole-heartedly approve of such things.)


---
Wait... You didn't update any of that NuGet crap, did you? Or update anything at all, besides the exception of .NET 4.8 (if it even asked that)?

**Comment by tass23** [comment]
> >So I've got a different set up than you. VS14, I may not have all the updated support software packages that you do...?
> 
> That's probably it. I got Visual Studio Community 2022. (It was the oldest version still available for download, haha.)
> 
> https://visualstudio.microsoft.com/vs/community/
> 
> As of writing this, that link takes you directly to the VS Community 2022 page, and the Download button is right there without having to scroll.
> 
> ---
> Why are you building it, out of curiosity? Just to see if you can? (If so, I whole-heartedly approve of such things.)
> 
> 
> ---
> Wait... You didn't update any of that NuGet crap, did you? Or update anything at all, besides the exception of .NET 4.8 (if it even asked that)?

No, I didn't update anything. I just opened the solution, which opened VS, I right-clicked on the project and selected Build. Then those 2 errors appeared.

I can't get VS22 because I'm on Win7. I think I can go up to 16 maybe. Is there something added that I can't get being on 7 then?

To see if I can, and if I can then I was going to see about adding some features to Quest, mainly to demonstrate things in the UI, like thumbnails of themes to see colors, themes for the Quest UI, maybe poke around at some color formatting inside small code view (full code has it), but nothing that will affect the code going out. Just visuals inside Quest really.

**Comment by KVonGit** [comment]
Oh, I didn't right-click to do anything.

I left click on the top item in the tree on the right, just so VS is "focusing" on the whole solution.

Then I change the Debug dropdown to Release.

Then I click "Build" from the menu across the very top. Then click Build in that dropdown.

It seems silly, but I bet there are different outcomes each way.

**Comment by KVonGit** [comment]
>To see if I can, and if I can then I was going to see about adding some features to Quest, mainly to demonstrate things in the UI, like thumbnails of themes to see colors, themes for the Quest UI, maybe poke around at some color formatting inside small code view (full code has it), but nothing that will affect the code going out. Just visuals inside Quest really.

Oh, I see. I was just wondering.

Building this converter in VS is a walk in the park compared to building Quest.

You have to do some stuff in the console in VS 2014 before you can get Quest to build, if memory serves. I won't go into any more details on Quest-specific stuff in VS here, to avoid crossing the streams.

**Comment by tass23** [comment]
> > To see if I can, and if I can then I was going to see about adding some features to Quest, mainly to demonstrate things in the UI, like thumbnails of themes to see colors, themes for the Quest UI, maybe poke around at some color formatting inside small code view (full code has it), but nothing that will affect the code going out. Just visuals inside Quest really.
> 
> Oh, I see. I was just wondering.
> 
> Building this converter in VS is a walk in the park compared to building Quest.
> 
> You have to do some stuff in the console in VS 2014 before you can get Quest to build, if memory serves. I won't go into any more details on Quest-specific stuff in VS here, to avoid crossing the streams.

I asked in the forums about adding visual features to Quest using the Source, so I'll see if anyone answers. But it looks like the interface is built using Quest libraries...? I see code for the Theme dropdown, and how it works changing the text boxes below to match. Now what I'm thinking is that I would like to add my own Themes that way too. Anyway, I opened a few files and poked around a bit, there are some errors, but the Build was successful when I did a test Build, so I know I can do that at least.

**Comment by KVonGit** [comment]
> it looks like the interface is built using Quest libraries

Yessiree!

All the GUI stuff with which you interact to create a game is coming from Quest libraries.

You don't need to rebuild Quest in VS to change that stuff.

You can just modify libraries in Quest's main folder and it has immediate effect. (You can also [create your own libraries which add GUI stuff](http://docs.textadventures.co.uk/quest/editor_user_interface_elements.html "http://docs.textadventures.co.uk/quest/editor_user_interface_elements.html").)

Every library that starts with "CoreEditor" in this folder is where the majority of that code lies :https://github.com/textadventures/quest/tree/master/WorldModel/WorldModel/Core

Some libraries (like CoreWearable) also have some extra code in them that adds things to the editor.

**Comment by KVonGit** [comment]
PS

Adding new stuff in the editor is very tedious.

I'm not trying to talk you out of it. It's just that I did it before to help during the update to Quest 5.8, and I disliked doing it. I usually don't mind the long, drawn-out, tedious stuff, but my brain just doesn't like looking at that particular code I guess.

**Comment by tass23** [comment]
> PS
> 
> Adding new stuff in the editor is very tedious.
> 
> I'm not trying to talk you out of it. It's just that I did it before to help during the update to Quest 5.8, and I disliked doing it. I usually don't mind the long, drawn-out, tedious stuff, but my brain just doesn't like looking at that particular code I guess.

Can you give me an example of what you mean?

I was expecting a form with controls on it, which matched various fields for the Quest interface in those libraries, but I didn't see anything right off the bat.

So you're saying that the UI is built with libraries that have the actual code to create drop downs, check boxes, text boxes, and not scripts. That's wild. I never would have guessed that without seeing these libraries.

But I would still need to Build it in VS in order to add things like Menu items, which I don't want to do.

Hmm, just for fun, I might try to port this through Access and create a VB file. It's old school, but it would be interesting. Need to keep that stuff sharp or I'll lose it, and since I'm staying with Win7, I need to keep the old school stuff fresh as long as possible! LOL

**Comment by KVonGit** [comment]
>Can you give me an example of what you mean?

What do you mean? Like a library that adds stuff to the editor?

Here is code from one of my old libraries. The highlighted lines (809 lines, to be exact) are all to do with adding stuff to the editor:

https://github.com/KVonGit/quest5-stuff/blob/main/libraries/archive/KVMasterLib.aslx#L3187-L3996

---
>But I would still need to Build it in VS in order to add things like Menu items, which I don't want to do.

The only thing you can't alter in the GUI without rebuilding is the stuff across the top, the usual windows menus and such.

The libraries create all the other stuff: the textboxes, the drop downs, the check boxes, the scripts, the specific drop-downs and such for each script, etc.

---
>Hmm, just for fun, I might try to port this through Access and create a VB file. It's old school, but it would be interesting. Need to keep that stuff sharp or I'll lose it, and since I'm staying with Win7, I need to keep the old school stuff fresh as long as possible! LOL

Hell yeah. If it works, that would be pretty cool.
